baseURL = "https://matthiassoell.github.io/iWIP/"
languageCode = "de-de"
title = "SciBlog iWIP"
theme = ["github.com/adityatelange/hugo-PaperMod", "github.com/joshed-io/reveal-hugo"]

[params]
  hideFooter = true
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowThemeToggle = true
  ShowRecentPosts = false
  mainSections = ["posts"]
  images = ["/iWIP/bilder/logo_siblog_iwip.png"]
  description = "Ich bin Prof. Dr. Matthias Söll vom Institut für Wirtschaftspädagogik (iWIP) der Universität Rostock und blogge mit Open Educational Resources über Wissenschaft und Bildung."

  [params.label]
    icon = "/iWIP/bilder/logo_siblog_iwip.png"
    text = ""  # optional: "" blendet den Titel aus, oder "SciBlog iWIP" lässt ihn stehen

[params.assets]
  customCSS = ["css/custom.css"]
  favicon = "/iWIP/favicon.ico"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "oer"
    name = "OER"
    url = "/oer/"
    weight = 10

  [[menu.main]]
    identifier = "bisy"
    name = "BiSy"
    url = "/bisy/"
    weight = 20

[outputs]
home = ["HTML"]
page = ["HTML", "Reveal"]

[outputFormats.Reveal]
name = "Reveal"
mediaType = "text/html"
baseName = "index"
isPlainText = false
isHTML = true
noUgly = true

[params.reveal_hugo]
theme = "white"
slide_number = "c/t"
custom_theme = "/iWIP/css/custom_reveal.css"