name: Deploy Preview of Hugo site

on:
  push:
    branches:
      - preview
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "preview"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.7
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Download Hugo Modules
        run: hugo mod get

      - name: Build Hugo with Preview Config
        run: |
          hugo --minify --config config.toml,config-preview.toml \
            --baseURL "${{ steps.pages.outputs.base_url }}/preview/"

      - name: Move site into preview subfolder
        run: |
          mkdir -p ./site/preview
          mv ./public/* ./site/preview/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Preview to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
